import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, CheckCircle2 } from "lucide-react";

import { Button } from "@/components/ui/button";

const SITE_URL = "https://www.filego.in";

export const metadata: Metadata = {
  title: "System Status | Filego",
  description:
    "Current operational status of Filego's tools, AI features, sign-in, and billing.",
  alternates: {
    canonical: `${SITE_URL}/status`,
  },
};

export const dynamic = "force-dynamic";

const components = [
  { name: "Website & Dashboard", description: "filego.in and account pages" },
  { name: "PDF Tools", description: "Merge, split, compress, convert, and edit" },
  { name: "Image Tools", description: "Compress, resize, crop, convert, and watermark" },
  { name: "Video & Audio Tools", description: "Trim, convert, compress, and merge" },
  { name: "Document & Office Tools", description: "Spreadsheet, JSON, XML, and Markdown utilities" },
  { name: "Security & Archive Tools", description: "Hashing, encryption, and archive formats" },
  { name: "Developer Tools", description: "JWT, regex, QR, and formatting utilities" },
  { name: "AI-Powered Tools", description: "OCR, summarization, resume parsing, and file chat" },
  { name: "Sign-in & Accounts", description: "Authentication and session management" },
  { name: "Billing & Payments", description: "Subscriptions, upgrades, and receipts" },
];

export default function StatusPage() {
  const lastChecked = new Date().toLocaleString("en-IN", {
    dateStyle: "medium",
    timeStyle: "short",
    timeZone: "Asia/Kolkata",
  });

  return (
    <main className="min-h-screen bg-background text-foreground">
      <section className="relative overflow-hidden border-b">
        <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_top,rgba(16,185,129,0.10),transparent_40%)]" />

        <div className="relative mx-auto max-w-4xl px-4 py-14 md:px-6 md:py-20">
          <div className="inline-flex items-center rounded-full border bg-background px-3 py-1 text-xs text-muted-foreground">
            System Status
          </div>

          <div className="mt-4 flex flex-wrap items-center gap-3">
            <span className="flex h-3 w-3 shrink-0 items-center justify-center">
              <span className="absolute h-3 w-3 animate-ping rounded-full bg-emerald-500/60" />
              <span className="relative h-2.5 w-2.5 rounded-full bg-emerald-500" />
            </span>
            <h1 className="text-2xl font-semibold tracking-tight sm:text-4xl">
              All systems operational
            </h1>
          </div>

          <p className="mt-3 text-sm leading-6 text-muted-foreground sm:text-base">
            This page reflects the current status of Filego&rsquo;s tools, AI features, and
            account services. It&rsquo;s reviewed manually, not generated by automated
            monitoring.
          </p>

          <p className="mt-1 text-xs text-muted-foreground">Last checked: {lastChecked} IST</p>
        </div>
      </section>

      <section className="border-b">
        <div className="mx-auto max-w-4xl px-4 py-10 md:px-6 md:py-14">
          <p className="text-xs font-medium text-muted-foreground">Components</p>
          <h2 className="mt-2 text-xl font-semibold tracking-tight sm:text-2xl">
            Status by service
          </h2>

          <div className="mt-6 divide-y divide-border/60 overflow-hidden rounded-2xl border border-border/60">
            {components.map((component) => (
              <div
                key={component.name}
                className="flex items-center justify-between gap-4 bg-card px-4 py-3.5 sm:px-5"
              >
                <div className="min-w-0">
                  <p className="text-sm font-medium text-foreground">{component.name}</p>
                  <p className="mt-0.5 text-xs text-muted-foreground">{component.description}</p>
                </div>
                <span className="inline-flex shrink-0 items-center gap-1.5 rounded-full border border-emerald-500/20 bg-emerald-500/10 px-2.5 py-1 text-xs font-medium text-emerald-600 dark:text-emerald-400">
                  <CheckCircle2 className="h-3.5 w-3.5" />
                  Operational
                </span>
              </div>
            ))}
          </div>

          <div className="mt-4 rounded-2xl border border-border/60 bg-muted/30 p-4 text-xs leading-5 text-muted-foreground sm:text-sm">
            Most Filego tools process files directly in your browser, so they generally
            keep working even during account, sign-in, or billing issues. Only AI-powered
            features and payments depend on backend services.
          </div>
        </div>
      </section>

      <section className="border-b">
        <div className="mx-auto max-w-4xl px-4 py-10 md:px-6 md:py-14">
          <p className="text-xs font-medium text-muted-foreground">Incident history</p>
          <h2 className="mt-2 text-xl font-semibold tracking-tight sm:text-2xl">
            Past 90 days
          </h2>

          <div className="mt-6 rounded-2xl border border-dashed border-border/60 p-8 text-center">
            <p className="text-sm text-muted-foreground">No incidents reported.</p>
          </div>
        </div>
      </section>

      <section>
        <div className="mx-auto max-w-4xl px-4 py-12 text-center md:px-6 md:py-16">
          <h2 className="text-xl font-semibold tracking-tight sm:text-2xl">
            Running into something not listed here?
          </h2>
          <p className="mx-auto mt-2 max-w-xl text-sm text-muted-foreground">
            Let us know what you&rsquo;re seeing and we&rsquo;ll take a look.
          </p>

          <div className="mt-6 flex flex-wrap items-center justify-center gap-3">
            <Button asChild className="rounded-xl">
              <Link href="/contact">
                Contact support
                <ArrowRight className="ml-2 h-4 w-4" />
              </Link>
            </Button>
            <Button asChild variant="outline" className="rounded-xl">
              <Link href="/help">Visit Help Center</Link>
            </Button>
          </div>
        </div>
      </section>
    </main>
  );
}
